/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardStocksRouteImport } from './routes/dashboard/stocks'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardPredictionsRouteImport } from './routes/dashboard/predictions'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardStocksSymbolRouteImport } from './routes/dashboard/stocks.$symbol'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStocksRoute = DashboardStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPredictionsRoute = DashboardPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStocksSymbolRoute = DashboardStocksSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => DashboardStocksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stocks': typeof DashboardStocksRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/stocks/$symbol': typeof DashboardStocksSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stocks': typeof DashboardStocksRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/stocks/$symbol': typeof DashboardStocksSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stocks': typeof DashboardStocksRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/stocks/$symbol': typeof DashboardStocksSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/predictions'
    | '/dashboard/settings'
    | '/dashboard/stocks'
    | '/dashboard/'
    | '/dashboard/stocks/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/admin'
    | '/dashboard/predictions'
    | '/dashboard/settings'
    | '/dashboard/stocks'
    | '/dashboard'
    | '/dashboard/stocks/$symbol'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/predictions'
    | '/dashboard/settings'
    | '/dashboard/stocks'
    | '/dashboard/'
    | '/dashboard/stocks/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stocks': {
      id: '/dashboard/stocks'
      path: '/stocks'
      fullPath: '/dashboard/stocks'
      preLoaderRoute: typeof DashboardStocksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/predictions': {
      id: '/dashboard/predictions'
      path: '/predictions'
      fullPath: '/dashboard/predictions'
      preLoaderRoute: typeof DashboardPredictionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stocks/$symbol': {
      id: '/dashboard/stocks/$symbol'
      path: '/$symbol'
      fullPath: '/dashboard/stocks/$symbol'
      preLoaderRoute: typeof DashboardStocksSymbolRouteImport
      parentRoute: typeof DashboardStocksRoute
    }
  }
}

interface DashboardStocksRouteChildren {
  DashboardStocksSymbolRoute: typeof DashboardStocksSymbolRoute
}

const DashboardStocksRouteChildren: DashboardStocksRouteChildren = {
  DashboardStocksSymbolRoute: DashboardStocksSymbolRoute,
}

const DashboardStocksRouteWithChildren = DashboardStocksRoute._addFileChildren(
  DashboardStocksRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardPredictionsRoute: typeof DashboardPredictionsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStocksRoute: typeof DashboardStocksRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardPredictionsRoute: DashboardPredictionsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStocksRoute: DashboardStocksRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
